name: Test Dev CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev

permissions:
  id-token: write
  contents: read

env:
  REGION: ap-southeast-1
  ECR_REPO: 567630311114.dkr.ecr.ap-southeast-1.amazonaws.com/helicap-test-repo
  DEV_ASSUME_ROLE_ARN: arn:aws:iam::615908245893:role/helicap-github-deployment-dev
  DEV_ECS_CLUSTER_NAME: helicap-dev
  DEV_ECS_SERVICE_NAME: helicap-dev-api-analytics
  GITHUB_ACTIONS_ROLE_ARN: arn:aws:iam::567630311114:role/Gitlab-test-oidc

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.REGION }}
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO || { echo "ECR login failed"; exit 1; }
      - name: Build and Push Image (Test Repo)
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t $ECR_REPO:latest . || { echo "Docker build failed"; exit 1; }
          docker tag $ECR_REPO:latest $ECR_REPO:$IMAGE_TAG
          docker push $ECR_REPO:latest || { echo "Docker push failed"; exit 1; }
          docker push $ECR_REPO:$IMAGE_TAG || { echo "Docker push failed"; exit 1; }
      - name: Clean up old ECR images
        run: |
          aws ecr batch-delete-image --repository-name $(echo $ECR_REPO | cut -d'/' -f2) --image-ids "$(aws ecr list-images --repository-name $(echo $ECR_REPO | cut -d'/' -f2) --filter tagStatus=UNTAGGED --query 'imageIds[*]' --output json)" || echo "No untagged images to delete"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.DEV_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.REGION }}
      - name: List ECS Clusters and Services
        run: |
          echo "Listing ECS clusters in dev account..."
          aws ecs list-clusters --region "${REGION}" || { echo "Failed to list clusters"; exit 1; }
          echo "Listing services in cluster ${DEV_ECS_CLUSTER_NAME}..."
          aws ecs list-services --cluster "${DEV_ECS_CLUSTER_NAME}" --region "${REGION}" || { echo "Failed to list services"; exit 1; }
          echo "Describing service ${DEV_ECS_SERVICE_NAME} in cluster ${DEV_ECS_CLUSTER_NAME}..."
          aws ecs describe-services --cluster "${DEV_ECS_CLUSTER_NAME}" --services "${DEV_ECS_SERVICE_NAME}" --region "${REGION}" || { echo "Failed to describe service"; exit 1; }
