name: Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint-success
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a dummy lint
        run: echo "Lint check passed test ✅"
